# 开发环境配置
FROM nginx:alpine

# 安装必要的工具（开发时可能需要）
RUN apk add --no-cache curl vim

# 复制nginx配置文件
RUN rm -rf /etc/nginx/conf.d/*
COPY site-nginx.conf /etc/nginx/conf.d/default.conf
# 复制网页文件
COPY src/ /usr/share/nginx/html/

# 暴露端口
EXPOSE 80

# 启动Nginx
CMD ["nginx", "-g", "daemon off;"]