# Dockerfile.django
FROM python:3.10

# 设置环境变量
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 安装系统依赖
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目文件
COPY src/django /app/

# 暴露端口
EXPOSE 8000

# 收集静态文件
RUN python manage.py collectstatic --noinput

# 启动Django开发服务器
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]