# Generated by Django 5.2.9 on 2026-05-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mailmessage',
            new_name='sendmail_ma_sender__b3e5be_idx',
            old_name='sendmail_ma_sender__ec983e_idx',
        ),
        migrations.RenameIndex(
            model_name='mailrecipient',
            new_name='sendmail_ma_recipie_141ffc_idx',
            old_name='sendmail_ma_recipie_a8e6ec_idx',
        ),
    ]
