PERMISSION_NODES = [
    {
        'node': 'permissions.table.edit',
        'label': '编辑权限表',
        'category': '权限管理',
        'description': '允许进入权限管理页面，并编辑各用户权限。',
    },
    {
        'node': 'permissions.table.view',
        'label': '查看权限表',
        'category': '权限管理',
        'description': '允许只读查看权限表。',
    },
    {
        'node': 'permissions.audit.view',
        'label': '查看授权审计',
        'category': '权限管理',
        'description': '允许查看权限变更历史。',
    },
    {
        'node': 'users.read',
        'label': '查看用户',
        'category': '用户',
        'description': '允许读取用户列表和用户基础信息。',
    },
    {
        'node': 'users.create',
        'label': '创建用户',
        'category': '用户',
        'description': '允许新增普通用户。',
    },
    {
        'node': 'users.update',
        'label': '编辑用户',
        'category': '用户',
        'description': '允许修改用户基础资料、启停状态。',
    },
    {
        'node': 'users.password.reset',
        'label': '重置用户密码',
        'category': '用户',
        'description': '允许为其他用户重置密码。',
    },
    {
        'node': 'account.username.update',
        'label': '修改自己的用户名',
        'category': '个人中心',
        'description': '允许当前登录用户修改自己的用户名。',
    },
    {
        'node': 'account.password.update',
        'label': '修改自己的密码',
        'category': '个人中心',
        'description': '允许当前登录用户在提供旧密码后修改自己的登录密码。',
    },
    {
        'node': 'account.navbar_title.update',
        'label': '更改导航栏标题',
        'category': '个人中心',
        'description': '允许当前登录用户更改全站导航栏标题。',
    },
    {
        'node': 'files.list.own',
        'label': '查看自己的文件列表',
        'category': '文件',
        'description': '允许列出当前用户自己的文件。',
    },
    {
        'node': 'files.list.all',
        'label': '查看全部文件列表',
        'category': '文件',
        'description': '允许列出所有用户文件。',
    },
    {
        'node': 'files.list.path.?',
        'label': '查看指定路径文件列表',
        'category': '文件',
        'description': '允许列出指定路径文件。',
    },
    {
        'node': 'files.read.own',
        'label': '读取自己的文件',
        'category': '文件',
        'description': '允许预览或读取当前用户自己的文件内容。',
    },
    {
        'node': 'files.read.all',
        'label': '读取全部文件',
        'category': '文件',
        'description': '允许预览或读取所有用户文件内容。',
    },
    {
        'node': 'files.read.path.?',
        'label': '读取指定路径文件',
        'category': '文件',
        'description': '允许预览或读取指定路径文件内容。',
    },
    {
        'node': 'files.upload.own',
        'label': '上传自己的文件',
        'category': '文件',
        'description': '允许向自己的空间上传文件。',
    },
    {
        'node': 'files.upload.path.?',
        'label': '上传自己的文件到指定路径',
        'category': '文件',
        'description': '允许向指定路径上传文件。',
    },
    {
        'node': 'files.download.own',
        'label': '下载自己的文件',
        'category': '文件',
        'description': '允许下载当前用户自己的文件。',
    },
    {
        'node': 'files.download.all',
        'label': '下载全部文件',
        'category': '文件',
        'description': '允许下载所有用户文件。',
    },
    {
        'node': 'files.download.path.?',
        'label': '下载指定路径文件',
        'category': '文件',
        'description': '允许下载指定路径文件。',
    },
    {
        'node': 'files.rename.own',
        'label': '重命名自己的文件',
        'category': '文件',
        'description': '允许重命名当前用户自己的文件。',
    },
    {
        'node': 'files.rename.all',
        'label': '重命名全部文件',
        'category': '文件',
        'description': '允许重命名所有用户文件。',
    },
    {
        'node': 'files.rename.path.?',
        'label': '重命名指定路径文件',
        'category': '文件',
        'description': '允许重命名指定路径文件。',
    },
    {
        'node': 'files.move.own',
        'label': '移动自己的文件',
        'category': '文件',
        'description': '允许移动当前用户自己的文件。',
    },
    {
        'node': 'files.move.all',
        'label': '移动全部文件',
        'category': '文件',
        'description': '允许移动所有用户文件。',
    },
    {
        'node': 'files.move.path.?',
        'label': '移动指定路径文件',
        'category': '文件',
        'description': '允许移动指定路径文件。',
    },
    {
        'node': 'files.delete.own',
        'label': '删除自己的文件',
        'category': '文件',
        'description': '允许删除当前用户自己的文件记录。',
    },
    {
        'node': 'files.delete.all',
        'label': '删除全部文件',
        'category': '文件',
        'description': '允许删除所有用户文件记录。',
    },
    {
        'node': 'files.delete.path.?',
        'label': '删除指定路径文件',
        'category': '文件',
        'description': '允许删除指定路径文件记录。',
    },
    {
        'node': 'files.share.own',
        'label': '分享自己的文件',
        'category': '文件',
        'description': '允许为当前用户自己的文件创建分享。',
    },
    {
        'node': 'files.share.all',
        'label': '分享全部文件',
        'category': '文件',
        'description': '允许为所有用户文件创建分享。',
    },
    {
        'node': 'files.share.path.?',
        'label': '分享指定路径文件',
        'category': '文件',
        'description': '允许为指定路径文件创建分享。',
    },
    {
        'node': 'shares.view.own',
        'label': '查看自己的分享',
        'category': '分享',
        'description': '允许查看当前用户创建的分享链接。',
    },
    {
        'node': 'shares.view.all',
        'label': '查看全部分享',
        'category': '分享',
        'description': '允许查看所有分享链接。',
    },
    {
        'node': 'shares.revoke.own',
        'label': '撤销自己的分享',
        'category': '分享',
        'description': '允许撤销当前用户创建的分享链接。',
    },
    {
        'node': 'shares.revoke.all',
        'label': '撤销全部分享',
        'category': '分享',
        'description': '允许撤销所有分享链接。',
    },
    {
        'node': 'preview.use',
        'label': '使用文件预览',
        'category': '工具',
        'description': '允许调用文件预览能力。',
    },
    {
        'node': 'search.use',
        'label': '使用搜索',
        'category': '工具',
        'description': '允许使用文件搜索能力。',
    },
    {
        'node': 'audit.view',
        'label': '查看审计日志',
        'category': '系统',
        'description': '允许查看系统审计日志。',
    },
    {
        'node': 'system.health.view',
        'label': '查看系统状态',
        'category': '系统',
        'description': '允许查看健康检查、运行状态等只读系统信息。',
    },
]


def permission_node_names():
    """Return built-in permission node names."""
    return [item['node'] for item in PERMISSION_NODES]
