"""
Django settings for project project.
Generated by 'django-admin startproject' using Django 4.2.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent.parent
SQLITE_DB_PATH = Path(
    os.environ.get('SMARTMEDIADISK_SQLITE_PATH', BASE_DIR / 'db' / 'db.sqlite3')
)
SQLITE_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
SMARTMEDIADISK_STORAGE_PATH = Path(
    os.environ.get('SMARTMEDIADISK_STORAGE_PATH', REPO_ROOT / 'data' / 'storage')
)
SMARTMEDIADISK_UPLOAD_TEMP_PATH = Path(
    os.environ.get('SMARTMEDIADISK_UPLOAD_TEMP_PATH', REPO_ROOT / 'data' / 'upload-tmp')
)
SMARTMEDIADISK_STORAGE_PATH.mkdir(parents=True, exist_ok=True)
SMARTMEDIADISK_UPLOAD_TEMP_PATH.mkdir(parents=True, exist_ok=True)

SECRET_KEY = 'django-insecure-1234567890qwerty'  # 在生产环境中应使用环境变量
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'helloworld',
    'sign',
    'files',
    'random32767',
    'db_test',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# 使用SQLite数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_DB_PATH,
    }
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 2 * 1024 * 1024 * 1024))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024))
