# Generated by Django 5.2.9 on 2026-05-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_shared_directory_compat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directoryentry',
            new_name='files_direc_parent__d1d949_idx',
            old_name='files_direc_parent__c7e434_idx',
        ),
        migrations.RenameIndex(
            model_name='fileentry',
            new_name='files_filee_owner_i_689203_idx',
            old_name='files_filee_owner_i_89e24b_idx',
        ),
        migrations.RenameIndex(
            model_name='fileentry',
            new_name='files_filee_name_e8e1c7_idx',
            old_name='files_filee_name_b9b0d9_idx',
        ),
        migrations.RenameIndex(
            model_name='fileentry',
            new_name='files_filee_created_d42762_idx',
            old_name='files_filee_created_febc67_idx',
        ),
    ]
